[package]
name = "zipline-mgr"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "winds"
path = "src/winds.rs"

[[bin]]
name = "line"
path = "src/line.rs"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
thiserror = "2.0.12"
